// Now Playing Movies
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';
export const GET_NOW_PLAYING_MOVIES_FAILURE = 'GET_NOW_PLAYING_MOVIES_FAILURE';

// Popular Movies
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILURE = 'GET_POPULAR_MOVIES_FAILURE';

// Upcoming Movies
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_FAILURE = 'GET_UPCOMING_MOVIES_FAILURE';

// Movie Details
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

// Movie Credits
export const GET_MOVIE_CREDITS = 'GET_MOVIE_CREDITS';
export const GET_MOVIE_CREDITS_SUCCESS = 'GET_MOVIE_CREDITS_SUCCESS';
export const GET_MOVIE_CREDITS_FAILURE = 'GET_MOVIE_CREDITS_FAILURE';

// Movie Recommendations
export const GET_MOVIE_RECOMMENDATIONS = 'GET_MOVIE_RECOMMENDATIONS';
export const GET_MOVIE_RECOMMENDATIONS_SUCCESS = 'GET_MOVIE_RECOMMENDATIONS_SUCCESS';
export const GET_MOVIE_RECOMMENDATIONS_FAILURE = 'GET_MOVIE_RECOMMENDATIONS_FAILURE';

// Account Details
export const GET_ACCOUNT_DETAILS = 'GET_ACCOUNT_DETAILS';
export const GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';
export const GET_ACCOUNT_DETAILS_FAILURE = 'GET_ACCOUNT_DETAILS_FAILURE';

// Watchlist
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_WATCHLIST_SUCCESS = 'ADD_TO_WATCHLIST_SUCCESS';
export const ADD_TO_WATCHLIST_FAILURE = 'ADD_TO_WATCHLIST_FAILURE';

export const GET_WATCHLIST = 'GET_WATCHLIST';
export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS';
export const GET_WATCHLIST_FAILURE = 'GET_WATCHLIST_FAILURE';

// Clear errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
